/*
JuiceFS console API

Testing RegionAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/menwenjun/jfs-ee-console-go-sdk"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_RegionAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RegionAPIService RegionsGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RegionAPI.RegionsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RegionAPIService RegionsRegionIDGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var regionID int32

		resp, httpRes, err := apiClient.RegionAPI.RegionsRegionIDGet(context.Background(), regionID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RegionAPIService RegionsRegionIDMetricsGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var regionID int32

		resp, httpRes, err := apiClient.RegionAPI.RegionsRegionIDMetricsGet(context.Background(), regionID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RegionAPIService RegionsRegionIDTrashtimeGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var regionID int32

		resp, httpRes, err := apiClient.RegionAPI.RegionsRegionIDTrashtimeGet(context.Background(), regionID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RegionAPIService RegionsRegionIDTrashtimePut", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var regionID int32

		resp, httpRes, err := apiClient.RegionAPI.RegionsRegionIDTrashtimePut(context.Background(), regionID).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
