/*
JuiceFS console API

API of the JuiceFS console (https://juicefs.com/api/v1)

API version: 0.0.1
Contact: team@juicedata.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VolumesVolumeIDListTrashGet400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VolumesVolumeIDListTrashGet400Response{}

// VolumesVolumeIDListTrashGet400Response struct for VolumesVolumeIDListTrashGet400Response
type VolumesVolumeIDListTrashGet400Response struct {
	Error *string `json:"error,omitempty"`
}

// NewVolumesVolumeIDListTrashGet400Response instantiates a new VolumesVolumeIDListTrashGet400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVolumesVolumeIDListTrashGet400Response() *VolumesVolumeIDListTrashGet400Response {
	this := VolumesVolumeIDListTrashGet400Response{}
	return &this
}

// NewVolumesVolumeIDListTrashGet400ResponseWithDefaults instantiates a new VolumesVolumeIDListTrashGet400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVolumesVolumeIDListTrashGet400ResponseWithDefaults() *VolumesVolumeIDListTrashGet400Response {
	this := VolumesVolumeIDListTrashGet400Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *VolumesVolumeIDListTrashGet400Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VolumesVolumeIDListTrashGet400Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *VolumesVolumeIDListTrashGet400Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *VolumesVolumeIDListTrashGet400Response) SetError(v string) {
	o.Error = &v
}

func (o VolumesVolumeIDListTrashGet400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VolumesVolumeIDListTrashGet400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableVolumesVolumeIDListTrashGet400Response struct {
	value *VolumesVolumeIDListTrashGet400Response
	isSet bool
}

func (v NullableVolumesVolumeIDListTrashGet400Response) Get() *VolumesVolumeIDListTrashGet400Response {
	return v.value
}

func (v *NullableVolumesVolumeIDListTrashGet400Response) Set(val *VolumesVolumeIDListTrashGet400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableVolumesVolumeIDListTrashGet400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableVolumesVolumeIDListTrashGet400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVolumesVolumeIDListTrashGet400Response(val *VolumesVolumeIDListTrashGet400Response) *NullableVolumesVolumeIDListTrashGet400Response {
	return &NullableVolumesVolumeIDListTrashGet400Response{value: val, isSet: true}
}

func (v NullableVolumesVolumeIDListTrashGet400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVolumesVolumeIDListTrashGet400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


